### ISSUE TITLE
Set up Kanban-board 

### ISSUE THREAD

**Issue by andgarzonmal** [andgarzonmal/capstone-project-back-end#23]
![image](https://user-images.githubusercontent.com/95243996/196802244-39e9a15b-cb47-4bd8-b707-b08823a93250.png)

- link to [Github repo](https://github.com/andgarzonmal/capstone-project-back-end)
- link to [Github project](https://github.com/andgarzonmal/capstone-project-back-end/projects/1)
- We are 5 people on the team
> - @dqarias
> - @Daf98 
> - @Olamarx 
> - @andgarzonmal 
> - @Andyveloper

**Comment by vichuge** [comment]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

- It looks like some of the cards on the project don't have a description, I invite you to add this to every card.
<img width="425" alt="image" src="https://user-images.githubusercontent.com/20563252/196804628-5936a906-acea-4218-ab2d-594ce8dd0cf5.png">

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Meltrust** [comment]
Hi @vichuge,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

------
